### ISSUE TITLE
Is it possible to mute the audio during recording?

### ISSUE THREAD

**Issue by muranoki3** [christoph-phillips/pizzicato-recorder#1]
@christoph-phillips Thank you for your fantastic wrapper for Pizzicato 😆
Please let me know is it possible to mute the audio during recording?
I tried the following code, but the recorded audio has no sound. No wonder, though...

`
Pizzicato.volume = 0;
Pizzicato.Recorder.start();
sound.on('end', ()=>{
  Pizzicato.Recorder.stop('wav', blobToBase64)
});
sound.play();
`

**Comment by chrislehoczki** [comment]
@muranoki3 No problem! Just published an update - you now start the recorder with an options object with `{ mute: false / true }`. See README for full example

**Comment by muranoki3** [comment]
@christoph-phillips Wow, Amazing!!  I will try it. Thank you very much for your updating.
